# Generated by Django 5.0.2 on 2024-03-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentoIdentidad', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registroIca', models.CharField(max_length=100)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('frecuenciaAplicacion', models.IntegerField()),
                ('valorProducto', models.IntegerField()),
                ('periodoCarencia', models.IntegerField()),
                ('nombreHongo', models.CharField(max_length=100)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveroApp.labor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registroIca', models.CharField(max_length=100)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('frecuenciaAplicacion', models.IntegerField()),
                ('valorProducto', models.IntegerField()),
                ('fechaUltimaAplicacion', models.DateField()),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveroApp.labor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registroIca', models.CharField(max_length=100)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('frecuenciaAplicacion', models.IntegerField()),
                ('valorProducto', models.IntegerField()),
                ('periodoCarencia', models.IntegerField()),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveroApp.labor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCatastro', models.CharField(max_length=100)),
                ('municipioUbicacion', models.CharField(max_length=100)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveroApp.productor')),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipoCultivo', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveroApp.finca')),
            ],
        ),
        migrations.AddField(
            model_name='labor',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveroApp.vivero'),
        ),
    ]
